import React from "react";
import Paperbase from "../../Layouts/Base";

class About extends React.Component {
    render() {
        const aboutText = `
            <h2>Acknowledgment</h2>
            
            The development of this app was funded by the California Energy Commission under grant number EPC-16-057.

            <br /><br />

            To view other tools and software developed by the Grid Integration Systems and Mobility (GISMo) group within SLAC National Accelerator Laboratory visit https://gismo.slac.stanford.edu/
            
            <br /><br />

            SLAC National Accelerator Laboratory is operated for the US Department of Energy by Stanford University under Contract DE-AC02-76SF00515.

            <h2>Disclaimer</h2>

            These data sets and tool ("Tool") are provided by the SLAC National Accelerator Laboratory ("SLAC"), which is operated by Stanford University for the U.S. Department of Energy (the "DOE").
            
            <br /><br />

            Disclosure of this Tool is provided under the following conditions and warnings: (1) this Tool have been prepared for reference purposes only; (2) this Tool consists of or are based on estimates or assumptions made on a best-efforts basis, based upon expectations of current and future conditions at the time they were developed; and (3) this Tool was prepared with information available at the time their development and are subject to change without notice.
            
            <br /><br />

            The user understands that DOE/SLAC/STANFORD UNIVERSITY are not obligated to provide the user with any support, consulting, training or assistance of any kind with regard to the use of the Tool or to provide the user with any updates, revisions or new versions thereof. DOE, SLAC, and STANFORD UNIVERSITY do not guarantee or endorse any results generated by use of the Tool, and user is entirely responsible for the results and any reliance on the results or the Tool in general.
            
            <br /><br />

            USER AGREES TO INDEMNIFY DOE/SLAC/STANFORD UNIVERSITY AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, AGENTS, AND EMPLOYEES AGAINST ANY CLAIM OR DEMAND, INCLUDING REASONABLE ATTORNEYS' FEES, RELATED TO USER'S USE OF THE METHODS. THE METHODS ARE PROVIDED BY DOE/SLAC/STANFORD UNIVERSITY "AS IS," AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL DOE/SLAC/STANFORD UNIVERSITY BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO CLAIMS ASSOCIATED WITH THE LOSS OF DATA OR PROFITS, THAT MAY RESULT FROM AN ACTION IN CONTRACT, NEGLIGENCE OR OTHER TORTIOUS CLAIM THAT ARISES OUT OF OR IN CONNECTION WITH THE ACCESS, USE OR PERFORMANCE OF THE METHODS.
            
            <br /><br />
            
            The user agrees to credit the U.S. Department of Energy (DOE)/SLAC/STANFORD UNIVERSITY in any publication that results from the use of the Tool. The names DOE/SLAC/STANFORD UNIVERSITY, however, may not be used in any publication in such a way as to endorse any results generated by use of the Tool, or in any advertising or publicity to endorse or promote any products or commercial entities, unless specific written permission is obtained from DOE/SLAC/STANFORD UNIVERSITY.
        `;

        return (
            <div>
                <Paperbase isTextContent={true} content={aboutText} />
            </div>
        );
    }
}

export default About;
