# Generated by Django 2.2.4 on 2020-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadforecast',
            name='controlled',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='loadforecast',
            unique_together={('config', 'controlled')},
        ),
    ]
