# Generated by Django 2.2.4 on 2020-10-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_auto_20201028_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadforecastconfig',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='loadforecastconfig',
            unique_together=set(),
        ),
    ]
