# Generated by Django 2.2.4 on 2020-11-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0004_auto_20201030_2040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='netpresentvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='netpresentvalue',
            name='config',
        ),
        migrations.DeleteModel(
            name='LoadProfile',
        ),
        migrations.DeleteModel(
            name='NetPresentValue',
        ),
    ]
