# Generated by Django 2.2.4 on 2020-11-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0005_auto_20201111_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emissionconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='emissionconfig',
            name='lf_config',
        ),
        migrations.AlterUniqueTogether(
            name='gasconsumption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gasconsumption',
            name='config',
        ),
        migrations.AlterUniqueTogether(
            name='gasconsumptionconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gasconsumptionconfig',
            name='lf_config',
        ),
        migrations.AlterUniqueTogether(
            name='loadprofileconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='loadprofileconfig',
            name='lf_config',
        ),
        migrations.AlterUniqueTogether(
            name='netpresentvalueconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='netpresentvalueconfig',
            name='lf_config',
        ),
        migrations.DeleteModel(
            name='Emission',
        ),
        migrations.DeleteModel(
            name='EmissionConfig',
        ),
        migrations.DeleteModel(
            name='GasConsumption',
        ),
        migrations.DeleteModel(
            name='GasConsumptionConfig',
        ),
        migrations.DeleteModel(
            name='LoadProfileConfig',
        ),
        migrations.DeleteModel(
            name='NetPresentValueConfig',
        ),
    ]
