name: e3restore3

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - numpy>=1.13.3
  - pandas>=0.24.0
  - PyInstaller>=3.4.0
  - Pyomo==5.6.6
  - PyUtilib==5.7.1
  - scipy>=1.1.0
  - future==0.18.2
